### ISSUE TITLE
FALTA DE RAMA DE ENTREGA DEL RETO 004

### ISSUE THREAD

**Issue by AlejandroVinas** [mmasias/24-25-EDA1#259]
Buenas tardes Masias, 

Me disponia a entregar el reto 4 pero no hay rama de entrega
¿Hacemos el pull request al main o creas tu una rama?

**Comment by mmasias** [comment]
Ostras! ¿Cómo no he visto esto? 
Lo siento 😞 
Hacerlo a main, sí. Yo lo redirijo.

**Comment by mmasias** [comment]
> Ostras! ¿Cómo no he visto esto? Lo siento 😞 Hacerlo a main, sí. Yo lo redirijo.

Ya está creada la rama y redirigidas todas las entregas relativas al reto 4 hechas a main (o a otras ramas) a la rama adecuada.

Lo dicho: disculpar el despiste. Tenía que haberla creado en el momento que planteé el reto.

Manuel
